### ISSUE TITLE
Inquiry about Hardware Details and Availability of Model Checkpoints

### ISSUE THREAD

**Issue by MexicanLemonade** [JFChi/PLUE#1]
First of all, I would like to thank you for making the implementation publicly available. It's a valuable resource for the community.

I am currently engaged in research that closely aligns with your work, and I'm interested in understanding more about the computational resources that were employed in your experiments. Specifically, I would like to inquire about the approximate training time and hardware configurations for the continual-pretraining part of your paper for the Roberta model.

Additionally, if it's possible, I am interested in accessing the model checkpoints. Having access to these would greatly facilitate replicating and building upon your work. If they are available, could you please guide me on how they can be accessed or provide them if they are not already included in the repository?

Thank you very much for your time and assistance. I look forward to your response and to potentially collaborating or contributing to your repository in the future.

**Comment by JFChi** [comment]
Hi Yikang,

Thanks for your interest in our work. You can download all checkpoints via the bash script: https://github.com/JFChi/PLUE/blob/main/finetuning/download.sh.

For the training time and hardware, we use A100 80G GPUs and the continual-pretraining should be very fast (1-2 days to finish).
